docs/AboutUs.md

Scale down images for better readability.

Refactor AboutUs.md

---

docs/team/nicholaschungjunjie.md
src/main/java/item/ItemException.java
src/main/java/validation/validation.java

Validation class will be used for validating user commands.
ItemException class will be used to throw exceptions within the item package.

Add validation class and ItemException class

---

src/main/java/order/Order.java
src/main/java/order/OrderEntry.java
src/main/java/order/OrderInterface.java
src/main/java/order/OrderList.java

Add Order template and variables and methods

---

src/main/java/utility/Ui.java

Add UI methods for printing

---

src/main/java/app/MoneyGoWhere.java
src/main/java/item/ItemList.java
src/main/java/utility/Ui.java
text-ui-test/EXPECTED.TXT
text-ui-test/input.txt

Add listitem and deleteitem

---

src/main/java/app/MoneyGoWhere.java
src/main/java/item/Item.java
src/main/java/utility/Ui.java
src/main/java/validation/ItemValidation.java
src/main/java/validation/orderValidation.java

Resolves #28 
> Refactor for better readability
> 1. Extract checks into methods
> 2. Extract all error messages into Ui.java
> 
>Refactor item price validation
> 1. Ensure price is a valid double
> 2. Ensure price is non-negative
> 3. Ensure price is 2 decimal points
> 4. Ensure price is not empty
> 
>Refactor item name validation
> 1. Ensure length of name is less than or equal to 25 characters
> 2. Ensure name is not empty

Refactor additem feature and validation

---

src/main/java/utility/Ui.java
src/main/java/validation/orderValidation.java

1. Add new error messages in Ui for addorder related validations
2. Add validation for flag argument - has to be integer for item index and quantity
3. Add validation to check missing argument and missing flags

Refactor orderValidation 

---

src/main/java/app/MoneyGoWhere.java
src/main/java/validation/orderValidation.java
src/main/java/validation/validation.java

It will perform validation of inputs before adding the order entry.

Add addorder command for the handleCommmand method in MoneyGoWhere

---

src/main/java/app/MoneyGoWhere.java

Update code to adhere to Coding Conventions

---

src/main/java/app/MoneyGoWhere.java
src/main/java/validation/ItemValidation.java
src/test/java/seedu/duke/ItemTest.java

Refactor additem feature validation and add JUnit test

---

src/main/java/app/MoneyGoWhere.java
src/main/java/validation/orderValidation.java

1. To override validateAgument method in validation
2. Call it in MoneyGoWhere to do input validation for addorder

Refactor order validation class

---

src/main/java/app/MoneyGoWhere.java
src/test/java/seedu/duke/OrderTest.java

Add JUnit tests for add order feature

---

src/main/java/app/MoneyGoWhere.java
src/main/java/order/Order.java
src/main/java/order/OrderList.java
src/main/java/utility/Parser.java
src/main/java/utility/Ui.java

Added the logic behind adding orderEntries to an Order, and adding an order itself.

Add functionality to add OrderEntry and Order

---

src/main/java/app/MoneyGoWhere.java
src/main/java/exception/InvalidArgumentException.java
src/main/java/exception/InvalidCommandException.java
src/main/java/exception/InvalidFlagException.java
src/main/java/exception/ItemException.java
src/main/java/item/Item.java
src/main/java/item/ItemList.java
src/main/java/order/Order.java
src/main/java/order/OrderInterface.java
src/main/java/order/OrderList.java
src/main/java/utility/Parser.java
src/main/java/utility/Ui.java
src/main/java/validation/ItemValidation.java
src/main/java/validation/OrderValidation.java
src/main/java/validation/Validation.java
src/test/java/seedu/duke/ItemTest.java
src/test/java/seedu/duke/OrderTest.java
store/menu.json

1. Remove static variables
2. Call non-static variables by instance
3. Add javadocs comments for exception and order validation classes
4. Remove commented codes
5. Correct indentation

Refactor code according to the style checks

---

src/main/java/app/MoneyGoWhere.java
src/main/java/order/Order.java
src/test/java/seedu/duke/OrderTest.java
store/orders.json

Remove unused import

---

src/main/java/app/MoneyGoWhere.java
src/main/java/order/Order.java
store/menu.json
store/orders.json

Format DateTime for printing Orders

---

docs/UserGuide.md
src/main/java/utility/Ui.java

Fix error message and Add structure to UG

---

src/main/java/app/MoneyGoWhere.java
src/main/java/item/Menu.java
src/main/java/order/Order.java
src/main/java/order/Transactions.java
src/main/java/validation/item/DeleteItemValidation.java

Refactor Code: Rename itemList to Menu, orderList to Transactions

---

src/main/java/app/MoneyGoWhere.java

Fix item deletion

---

src/main/java/utility/Ui.java
src/main/java/validation/Validation.java

Add integer overflow handling

---

src/main/java/app/MoneyGoWhere.java
src/main/java/order/Order.java
src/main/java/utility/Ui.java
src/main/java/validation/order/AddMultipleOrderValidation.java
src/main/java/validation/order/AddOrderValidation.java
src/main/java/validation/order/OrderValidation.java
src/test/java/seedu/duke/ItemTest.java
src/test/java/seedu/duke/OrderTest.java
store/menu.json
store/orders.json

All single add order commands are handled correctly
1. Invalid flag
2. Invalid argument
3. Invalid index

Handle addorder -i validation

---

src/main/java/app/MoneyGoWhere.java
src/main/java/item/Menu.java
src/main/java/item/MenuAssistant.java
src/main/java/validation/item/AddItemValidation.java
src/main/java/validation/item/DeleteItemValidation.java

Refactor code according to coding standards

---

build.gradle
src/test/java/seedu/moneygowhere/OrderTest.java

Add JUnit tests for the Order class

Add JUnit tests

---

src/main/java/validation/order/AddOrderValidation.java

Fix bug in addorder method

---

src/main/java/order/Order.java

Fixed a bug where `addorder -i chicken -q 2:0` crashes the program

Fix order validation bug

---

docs/DeveloperGuide.md

Contribute to DG

---

src/main/java/app/MoneyGoWhere.java
src/main/java/utility/Ui.java

Print subtotal after each order is added successfully

---

src/main/java/app/MoneyGoWhere.java
src/main/java/order/Order.java
src/main/java/payment/Payment.java
src/main/java/payment/Refund.java
src/main/java/utility/Ui.java
src/main/java/validation/order/PaymentValidation.java
src/test/java/seedu/moneygowhere/OrderTest.java

Fixes #145 
1. User have to enter payment details immediately after adding an order
2. Payment type must be one of the following: cash/card/others and will be stored in json file
3. Amount must be more than subtotal

Add payment feature

---

docs/DeveloperGuide.md

Contribute to DG for refund order feature

---

src/test/java/seedu/moneygowhere/OrderNegativeTest.java

Will add on to this in future commits

Add negative test code

---

src/main/java/order/Order.java
src/main/java/order/OrderAssistant.java
src/main/java/validation/order/AddMultipleAddOrderValidation.java
src/main/java/validation/order/AddOrderValidation.java

Next time please say something if you're going to comment out so much of my old code, so I don't need to spend hours to read through and understand and figure out what is missing and what is going on

Fix broken addOrder commands

---

src/main/java/app/Router.java
src/main/java/order/Order.java
src/main/java/order/OrderAssistant.java

1. Remove the global variables in order class
2. Fix order.json (remove unnecessary fields)

Refactor order class

---

src/main/java/payment/Refund.java
src/main/java/payment/RefundAssistant.java
src/main/java/ui/TransactionUi.java

Fix refund order bugs

---

src/test/java/seedu/moneygowhere/OrderNegativeTest.java
src/test/java/seedu/moneygowhere/OrderTest.java
src/test/java/seedu/moneygowhere/TransactionNegativeTest.java
src/test/java/seedu/moneygowhere/TransactionTest.java

Added additional test cases to stress, boundary, and negative test Order and Transaction classes

Add additional tests

---

docs/DeveloperGuide.md
docs/team/yuanners.md
src/test/java/seedu/moneygowhere/OrderTest.java
src/test/java/seedu/moneygowhere/PaymentTest.java
src/test/java/seedu/moneygowhere/RefundTest.java

1. Add junit test cases for refund order and payment commands
2. Update DG on the make payment basic mode
3. Update PPP accordingly

Update DG and Junit tests

---

docs/UserGuide.md

Changed md image format to html

Fix broken icon
